# Generated by Django 6.0.7 on 2026-09-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='moderation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
